

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: image: springboot-ci-cd:latest

    container_name: image: springboot-ci-cd:latest

    ports:
      - "9090:9090"

