

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-ci-cd:$build_number
    container_name: springboot-ci-cd:$build_number
    ports:
      - "9090:9090"

